table Details
	lineageTag: 65647d8f-2668-4df7-99b1-3716b4891bba

	column 'Order ID'
		dataType: string
		lineageTag: 150ee484-4f68-4d6f-afb5-172dffbae875
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 56ce8ce2-271e-483b-8163-584b096e1178
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: int64
		formatString: 0
		lineageTag: fa3a80ce-e213-41cc-85fb-64ef66480ce5
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: bff92ced-daac-41f0-a3b4-5ef36be48307
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 60aafa9b-b4f9-4af7-9734-df7dcd44478e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 47cdc6a7-9b58-43b0-abf0-389f69c6d926
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column PaymentMode
		dataType: string
		lineageTag: ee95fa79-08e1-4e2d-9b26-ca81351d3d0e
		summarizeBy: none
		sourceColumn: PaymentMode

		annotation SummarizationSetBy = Automatic

	column ADV = [Amount]/[Quantity]
		dataType: int64
		lineageTag: 28d2eb84-f8ee-48a0-b5af-68a1cd1e4a5b
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Details = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\csv file\Details.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Amount", Int64.Type}, {"Profit", Int64.Type}, {"Quantity", Int64.Type}, {"Category", type text}, {"Sub-Category", type text}, {"PaymentMode", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

